name: Books Data Import

on:
  push:
    paths:
      - .github/workflows/bookdigest.yml
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Corrected to run at the start of every hour

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Fetch newest
        uses: githubocto/flat@v3
        with: 
          http_url: https://www.googleapis.com/books/v1/volumes?q=subject:fiction&orderBy=newest
          downloaded_filename: newest.json

      - name: Add genre attribute using OpenAI
        run: |
          apt-get update && apt-get install -y python3 python3-pip
          pip3 install openai

          cat << 'EOF' > modify_json.py
          import json
          import openai
          import os

          openai.api_key = os.getenv("OPENAI_API_KEY")

          def get_genre(description):
              try:
                  response = openai.ChatCompletion.create(
                      model="gpt-3.5-turbo",
                      messages=[{"role": "system", "content": "Identify the genre of this book description."}, {"role": "user", "content": description}]
                  )
                  return response["choices"][0]["message"]["content"].strip()
              except Exception as e:
                  print(f"Error getting genre: {e}")
                  return "Unknown"

          with open("newest.json", "r") as file:
              data = json.load(file)

          for book in data.get("items", []):
              volume_info = book.get("volumeInfo", {})
              description = volume_info.get("description", "")
              if description:
                  genre = get_genre(description)
                  volume_info["genre"] = genre

          with open("newest.json", "w") as file:
              json.dump(data, file, indent=2)
          EOF

          python3 modify_json.py

          # Remove the temporary script
          rm modify_json.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || (
            git add newest.json
            git commit -m "Added genre attribute to book items using OpenAI"
            git push
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
