name: Books Data Import

on:
  push:
    paths:
      - .github/workflows/bookdigest.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight UTC

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch books from Google Books API
        run: |
          curl "https://www.googleapis.com/books/v1/volumes?q=subject:fiction&orderBy=newest&maxResults=40" -o google_books.json
      - name: Extract ISBN-13 values
        run: |
          cat google_books.json | jq -r '.items[]?.volumeInfo.industryIdentifiers[]? | select(.type=="ISBN_13") | .identifier' > isbn13s.txt
      - name: Fetch book details from ISBNdb
        run: |
          # Initialize an empty file for book details
          echo "[]" > books_details.json
          # Read the identifiers and fetch details from ISBNdb
          while IFS= read -r isbn; do
            response=$(curl -H "Authorization: ${ISBNDB_API_KEY}" "https://api2.isbndb.com/book/$isbn")
            # Check if the response is not null
            if [ "$(echo "$response" | jq -r '.book')" != "null" ]; then
              # Append the book details to the books_details.json
              jq --argjson new_book "$response" '. += [$new_book]' books_details.json > temp.json && mv temp.json books_details.json
            fi
          done < isbn13s.txt
        env:
          ISBNDB_API_KEY: ${{ secrets.ISBNDB_API_KEY }}

      - name: Commit and push books details JSON
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add books_details.json
          git commit -m "Add latest books details"
          git push origin main
