name: Books Data Import

on:
  push:
    paths:
      - .github/workflows/bookdigest.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight UTC

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch ISBN-10 values from Google Books API
        run: |
          curl "https://www.googleapis.com/books/v1/volumes?q=subject:fiction&orderBy=newest&maxResults=40" | jq -r '.items[].volumeInfo.industryIdentifiers[] | select(.type=="ISBN_10") | .identifier' > isbns.txt

      - name: Retrieve book info from ISBNdb
        run: |
          while IFS= read -r isbn; do
            curl -H "Authorization: ${ISBNDB_API_KEY}" "https://api2.isbndb.com/book/${isbn}" -o "book_${isbn}.json"
          done < isbns.txt
        env:
          ISBNDB_API_KEY: ${{ secrets.ISBNDB_API_KEY }}

      - name: Upload fetched data
        uses: actions/upload-artifact@v3
        with:
          name: books-json
          path: |
            book_*.json
            isbns.txt
